In [1]:
import pandas as pd

# analysis benchmark

In [13]:
df_benchmark = pd.read_csv('./files/email_benchmark1.csv', header=1, sep=', ' )
df_benchmark.head()

/tmp/ipykernel_24535/2091687483.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_benchmark = pd.read_csv('./files/email_benchmark1.csv', header=1, sep=', ' )

,query,email_result,email,issue
0,ferdinand punkt reicht at bla punkt com,ferdinand.reicht@bla.com,ferdinand.reichl@bla.com,voice
1,pedro punkt ebner at mail dot com,pedro.ebner@mail.com,pietro.ebner@mail.com,voice
2,meine email ist m strich martha holz at bla pu...,m-marthaholz@bla.com,n-mahrenholz@bla.com,voice
3,s punkt w at mercedes d e,s.w@mercedesde,s.w@mercedes.de,voice
4,nele punkt gürtler at mail dot com,nele.gürtler@mail.com,neele.gürtler@mail.com,voice

In [14]:
df_benchmark.groupby('issue').count()

           query  email_result  email
issue
luis          14            14     14
validator     11            11     11
voice        148           148    148

In [15]:
df_benchmark[df_benchmark.issue == 'validator']

,query,email_result,email,issue
11,steven andreas strich m dreizehn at bla dot com,andreas-mdreizehn@bla.com,stevenandreas-m13@bla.com,validator
15,das is t p neunzehn at gmail punkt com,istpneunzehn@gmail.com,ep19@gmail.com,validator
16,s punkt bartel vierzehn at tonline punkt com,s.bartelvierzehn@tonline.com,s.barthel14@t-online.com,validator
39,die punkt p at mercedes dot com,.p@mercedes.com,d.p@mercedes.com,validator
44,das ist p punkt k fünfzig at hotmail punkt com,p.kfünfzig@hotmail.com,p.k50@hotmail.com,validator
45,b strich lampi ne dreizehn at gmail dot com,b-lampinedreizehn@gmail.com,b-lampinen13@gmail.com,validator
50,s strich barenowska sechzehn at mercedes d e,s-barenowskasechzehn@mercedesde,s-baranauskas16@mercedes.de,validator
66,helen stefanie minus r vierzehn at gmail dot com,stefanie-rvierzehn@gmail.com,helenstefanie-r14@gmail.com,validator
92,u punkt wiedemann elf at gmx punkt com,u.wiedemannelf@gmx.com,u.widenmann11@gmx.com,validator
96,j punkt w vierzehn at gmx punkt d e,j.wvierzehn@gmx.de,j.w14@gmx.de,validator
153,g punkt neun juni neunzehn at mercedes punkt com,g.9junineunzehn@mercedes.com,g.nojumi19@mercedes.com,validator

In [16]:
df_benchmark[df_benchmark.issue == 'luis']

,query,email_result,email,issue
6,die adresse lautet mike hessam punkt s at tonl...,hessam.s@tonline.com,mikehessam.s@t-online.com,luis
9,andre nico punkt fink at gmx dot com,nico.fink@gmx.com,andrenico.fink@gmx.com,luis
25,hans georg punkt z at mercedes dot com,georg.z@mercedes.com,hansgeorg.z@mercedes.com,luis
27,meine email ist wie strich t at gmx d e,t@gmxde,w-t@gmx.de,luis
35,mark oliver punkt steyer at mail punkt com,oliver.steyer@mail.com,markoliver.steyer@mail.com,luis
36,silvia paula punkt s at gmx punkt d e,paula.s@gmx.de,silviapaula.s@gmx.de,luis
47,horst dieter punkt s at hotmail dot com,dieter.s@hotmail.com,horst-dieter.s@hotmail.com,luis
54,meine email ist james william punkt meister at...,william.meister@mercedes.com,jameswilliam.meister@mercedes.com,luis
55,mark oliver punkt v at bla d e,oliver.v@blade,markoliver.v@bla.de,luis
74,die adresse lautet ernst august strich hertz a...,hertz@test.com,ernstaugust-hertz@test.com,luis
90,mike hessam punkt walbeck at test punkt com,hessam.walbeck@test.com,mikehessam.walbeck@test.com,luis
98,meine email ist christian franz punkt kiefer a...,franz.kiefer@mercedes.com,christianfranz.kiefer@mercedes.com,luis
118,hans henning punkt ayten at gmail dot com,henning.ayten@gmail.com,hans-henning.ayten@gmail.com,luis
165,jörn hendrik minus schierling wanze at mail do...,schierlingwanze@mail.com,jan-hendrik-schirling-wantzen@mail.com,luis

In [25]:
len([i for i in df_benchmark[df_benchmark.issue == 'voice'].email_result.apply(lambda x: x.split('@')[1]) if '.' not in i])

70

In [24]:
[i for i in df_benchmark[df_benchmark.issue == 'voice'].email_result.apply(lambda x: x.split('@')[1]).unique() if '.' not in i]

['mercedesde',
 'gmailde',
 'gmxde',
 'tonlinede',
 'testde',
 'blade',
 'hotmailde',
 'mailde']