In [13]:
import pandas as pd

# analysis benchmark

In [14]:
df_benchmark = pd.read_csv('./files/lpr_benchmark.csv', header=1, sep=', ' )
df_benchmark.head()

/tmp/ipykernel_15012/3040310035.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_benchmark = pd.read_csv('./files/lpr_benchmark.csv', header=1, sep=', ' )

,query,lpr_result,lpr,cplquery,luis_entity,issue
0,c l z tower einfach vier neun,NaN,CLZ-HA1649,das ist c l z tower einfach vier neun,c l z tower einfach vier neun,voice
1,r o w p p sieben acht zwei sieben,ROW-PP7827,ROW-PP7627,das ist ROW-PP7827,r o w p p sieben acht zwei sieben,voice
2,r g r t eins sechs sechs null,RG-RT166,RG-RT1660,das ist RG-RT166null,r g r t eins sechs sechs,luis
3,video b j fünf eins eins drei,NaN,TDO-BJ5113,das ist video b j fünf eins eins drei,video b j fünf,luis
4,s r w w k neun eins eins null,NaN,FRW-WK9110,das ist s r w w k neun eins eins null,s r w w k neun,luis

In [15]:
df_benchmark.groupby('issue').count()

       query  lpr_result  lpr  cplquery  luis_entity
issue
luis     189         151  189       189          189
voice    119          67  119       115          115

In [16]:
df_benchmark[df_benchmark.issue == 'luis']

,query,lpr_result,lpr,cplquery,luis_entity,issue
2,r g r t eins sechs sechs null,RG-RT166,RG-RT1660,das ist RG-RT166null,r g r t eins sechs sechs,luis
3,video b j fünf eins eins drei,NaN,TDO-BJ5113,das ist video b j fünf eins eins drei,video b j fünf,luis
4,s r w w k neun eins eins null,NaN,FRW-WK9110,das ist s r w w k neun eins eins null,s r w w k neun,luis
5,m m u s zwei vier foils,MM-US24,MM-US2455,das ist MM-US24foils,m m u s zwei vier,luis
7,o d x k sieben zwei eins drei,OD-XK72,OD-XK7213,das ist OD-XK72eins drei,o d x k sieben zwei,luis
...,...,...,...,...,...,...
303,l s n x b zwei neun eins eins,LSN-XB29,LSN-XB2911,das ist LSN-XB29eins eins,l s n x b zwei neun,luis
304,r p q l voice eins eins eins,NaN,RP-QL5111,das ist r p q l voice eins eins eins,r p q l voice,luis
305,d l j z acht sieben drei eins,DL-JZ873,DL-JZ8731,das ist DL-JZ873eins,d l j z acht sieben drei,luis
306,g n p j k zwei sechs neun zwei,NaN,GNT-JK2692,das ist g n p j k zwei sechs neun zwei,g n p j k zwei sechs neun,luis
307,t asp p eins sieben eins zwei,NaN,CAS-PP1712,das ist t asp p eins sieben eins zwei,t asp p eins sieben,luis

In [21]:
df_benchmark[df_benchmark.issue == 'luis']['query'].values

array(['r g r t eins sechs sechs null', 'video b j fünf eins eins drei',
       's r w w k neun eins eins null', 'm m u s zwei vier foils',
       'o d x k sieben zwei eins drei', 'a n q w eins fünf vier eins',
       'b p y e zwei neun drei eins', 'wie o g o acht sechs vier neun',
       'e g r sechs fünf neun null', 'f f b f y fünf acht null sieben',
       'g n t h v sieben acht eins sechs', 'g t q foi vier eins zwei',
       'b h g l neun drinnen eins', 'm y t h sieben acht null zwei',
       's o n t fünf vier fünf eins', 'h b n n p drei fünf null null',
       's i v c neun acht vier eins', 'd w o zwei vier sieben eins',
       'a w b x acht drei eins eins', 'b i w d k sieben null vier drei',
       'a s l f z sechs sechs drei null', 'h l j c zwei zwei drei eins',
       's e b d i zwei sechs fünf null', 'w b s d d acht zwei neun eins',
       'b p s b acht vs acht eins', 'ähm s t k r voice null zwei',
       'wie u s m sechs sieben drei', 'es w b m eins fünf vier acht',
       'r u t r j sieben null fünf drei', 'g t x r sieben vier acht eins',
       'gehen l d acht vier eins acht', 'l g x t sechs vier null acht',
       'plz c d sieben acht sieben null', 'o a k n fünf neun eins zwei',
       'g t z x neun null null neun', 'w o b v k eins sechs eins null',
       'n e a f i vier vier null fünf', 'e m s s w drei drei eins drei',
       'wer x f sieben acht acht fünf', 'e i n p r sieben fünf vier null',
       'm u s c p sechs sechs null zwei', 'o f d s neun neun acht null',
       'r d g m u acht sieben eins eins', 'd l a u zwei vier eins null',
       'h o m l a drei drei drei null', 'e r z h u zwei drei drei eins',
       'hat sie p s sechs eins vier fünf',
       'k e y z sieben fünf eins null', 'a w o voice neun eins',
       'es r o b a neun fünf vier null', 'o d y p sieben drei eins acht',
       'w t m e s fünf sechs eins sechs', 'd l n c vier fünf sechs null',
       'd u f z fünf zwei null sechs', 'b r a n x sechs null null sieben',
       'a p f d fünf vier eins zwei', 'w o s a i drei acht null',
       'wie z l pe zwei sechs zwei eins',
       'a b g a a fünf sieben vier null', 'e i n q b eins fünf null null',
       'w t y a vier drei eins zwei', 'c o t f z zwei acht drei eins',
       'd m n s c drei zwei null eins', 'r l y e acht drei fünf null',
       'geil p w zwei sechs zwei acht', 'b o g kroko drin oder drinnen',
       'n v p v e sechs eins null zwei', 'v e k neun acht fünf null',
       'wie d s m r acht eins sechs drei',
       'h y w h vier sechs null sechs', 'n s j x sieben eins sieben',
       'o d n x drei eins eins zwei', 'l s a z g zwei sechs sechs eins',
       'ö h r j p fünf acht null drei', 'h p q i neun sechs null zwei',
       'die s j n drei zwei null acht', 'hi g x x neun zwei null drei',
       'm a k y b neun vier null acht', 'n t t l sieben neun zwei null',
       'z r h k drei sechs null null', 'b d f l b neun zwei neun null',
       's b g s einfach acht zwei null', 'l b z l t neun neun null vier',
       'w w k u sechs acht zwei', 'h k z y drei zwei drei null',
       'm k hatte k acht voyce null sechs', 'o h q q woist rief äs nun',
       'o v i n sechs drei zwei eins', 'h d r v acht zwei null drei',
       'b w a c sieben eins sechs eins', 's g c gehen vier sechs acht',
       'z z v d eins sieben vier drei', 'r o w d u vier neun sieben eins',
       'hauen g vier null zwei vier', 'm o q q sechs zwei sieben eins',
       'o e f e acht vier acht eins', 'die i d t neun null acht eins',
       't a s x z acht neun null vier', 'r d g d m neun vier acht drei',
       'w f h h zwei sechs null null', 'e f g o neun null vier eins',
       'h v b t eins drei fünf eins', 'm a k k a vier neun drei eins',
       'es b v neun eins drei sieben', 'm q h sechs vier eins neun',
       'r d h acht neun eins sieben', 'wir g h sieben zwei drei eins',
       'b c h h c fünf fünf sechs eins', 's t a z fünf neun eins drei',
       's p o m acht acht null sieben', 'm e t h h eins null drei null',
       'n o m i a neun null drei zwei', 'g e l h i drei zwei drei eins',
       'wie k i c sechs neun sechs drei', 's n o m sieben fünf neun null',
       'h s t p r sieben sechs zwei zwei',
       'h x o h sieben eins null zwei', 'wie r z o t vier null neun drei',
       's spd acht neun null zwei', 'b c acht vier vier eins',
       'h v l p v fünf null sechs eins',
       'wie b g n sieben drei acht sieben',
       'l ü n c c drei neun sieben null', 'k w l f sechs drei null null',
       'h a s w fünf eins sechs', 'a r t x d neun zwei drei null',
       'a s l d s vier sieben fünf eins', 'f d h b fünf null sechs',
       'g ö w f neun eins null drei', 'w i z w f vier sieben eins drei',
       'f f b t q fünf null null fünf', 'h d b j drei vier null fünf',
       's l v m vier sieben eins wolf', 'a n k r m zwei acht eins zwei',
       'patrick a x fünf null null sechs', 's r z r eins drei acht eins',
       'b i v q drei vier sieben null', 's h g n c vier null null sieben',
       'r a y u eins fünf vier eins', 'r w d v fünf acht null sechs',
       'g ö c t vier fünf null eins', 'es b v e acht neun sechs neun',
       's p n s p zwei sechs eins vier', 'w e n x w fünf null vier acht',
       's o b b fünf sieben drei eins', 'm e k v drei vier null zwei',
       'w e s w r voice nun eins eins',
       'n a i a p sieben neun sieben null',
       'k l z k u zwei neun null sieben', 's r t l neun eins sechs eins',
       'm e x p acht null eins', 'die a b q neun vier null eins',
       'n k v drei sieben null', 'g m f vier null drin',
       'k y a u sieben zwei eins sechs',
       'b k s n c sechs sieben neun eins',
       'm s t x w drei null eins sechs', 'a e f v neun null null sieben',
       'gehen o h zwei vier zwei wolf', 'p o h u l vier null neun',
       'wie m k h eins vier vier', 'n l i k sechs vier eins vier',
       's g s c eins sieben acht drei', 'n b e w neun vier null eins',
       'm s t v s drei sechs eins', 't ü v w neun neun eins zwei',
       'b b d f p fünf fünf null fünf', 'b k haus sieben null voyce',
       'u m p h drei fünf neun null', 'f k e x acht fünf zwei eins',
       'a u r u eins vier eins fünf', 't r s c acht sechs eins sechs',
       'e z i neun sieben fünf null', 'wie a ks u fünf acht drei acht',
       'f o r h u sieben neun vier null', 's i e o zwei neun null vier',
       'l w l w u neun drei zwei null', 'k ü n o m neun eins eins null',
       'h p q z zwei sechs eins neun', 'h i p t u sieben zwei null sechs',
       'n f o g zwei fünf eins', 'die k t s sieben sieben sieben null',
       't r t n sieben acht acht eins', 'o l u p acht acht eins drei',
       'l s n x b zwei neun eins eins', 'r p q l voice eins eins eins',
       'd l j z acht sieben drei eins', 'g n p j k zwei sechs neun zwei',
       't asp p eins sieben eins zwei'], dtype=object)